# -*- coding: utf-8 -*-
"""BANK_LOAN_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFgDMUbudCNKEkJcvunHiutIm-1M7dF2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
sns.set(style="whitegrid", palette="pastel")

df = pd.read_csv("/content/Cleaned_Loan_Bank_Data.csv")

df.head()

df.info()

df.shape

df.describe()

df.isnull().sum()

for i in ['Gender', 'Married', 'Dependents', 'Self_Employed','Credit_History']:
    df[i].fillna(df[i].mode()[0], inplace=True)

for col in ['LoanAmount', 'Loan_Amount_Term']:
    df[col].fillna(df[col].mean(), inplace=True)

df.isnull().sum()

df.drop('Loan_ID', axis=1, inplace=True)

categorical = ['Gender', 'Married', 'Education', 'Self_Employed', 'Credit_History', 'Property_Area', 'Loan_Status']

for i in categorical:
    sns.countplot(x=i, data=df, palette="coolwarm")
    plt.title(f"Distribution of {i}")
    plt.show()

df.head()

numerical = ['ApplicantIncome','CoapplicantIncome','LoanAmount',
             'Loan_Amount_Term']

for i in numerical:
    plt.hist(x=i, data=df)
    plt.title(f"Distribution of {i}")
    plt.show()

df['Total_Income'] = df['ApplicantIncome'] + df['CoapplicantIncome']

df.head()

sns.countplot(x='Credit_History', hue='Loan_Status', data=df, palette="Set2")
plt.title("Loan Approval by Credit History")
plt.show()


sns.countplot(x='Gender', hue='Loan_Status', data=df, palette="Set2")
plt.title("Loan Approval by Gender")
plt.show()


sns.countplot(x='Education', hue='Loan_Status', data=df, palette="Set3")
plt.title("Loan Approval by Education")
plt.show()


sns.scatterplot(x='Total_Income', y='LoanAmount', hue='Loan_Status', data=df)
plt.title("Total Income vs Loan Amount (by Approval Status)")
plt.show()

df.head()

corr = df[['ApplicantIncome','CoapplicantIncome','LoanAmount','Total_Income','Credit_History']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

sns.boxplot(x=df['ApplicantIncome'], color='orange')
plt.title("Outliers in Applicant Income")
plt.show()


sns.boxplot(x=df['LoanAmount'], color='lightblue')
plt.title("Outliers in Loan Amount")
plt.show()

"""> Applicants with Credit_History = 1 have higher approval rates.

> Graduates and Self-Employed individuals have slightly higher chances of approval.

> Higher income → slightly higher loan amounts, but credit history is the biggest driver.

> Most applications come from semi-Urban and urban property areas.

> And gender is also imp cause male have higher loan approval rate than females.
"""

summary = df.groupby('Loan_Status').agg({
    'ApplicantIncome': 'mean',
    'CoapplicantIncome': 'mean',
    'LoanAmount': 'mean',
    'Total_Income': 'mean'
}).reset_index()
print(summary)

plt.figure(figsize=(12,5))

# Boxplot before
plt.subplot(1,2,1)
sns.boxplot(x=df['Total_Income'])
plt.title('Before Outlier Treatment - Boxplot')

# Histogram before
plt.subplot(1,2,2)
sns.histplot(df['Total_Income'], kde=True, bins=30)
plt.title('Before Outlier Treatment - Distribution')

plt.show()

def cap_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    data[column] = np.where(data[column] > upper_limit, upper_limit,
                            np.where(data[column] < lower_limit, lower_limit, data[column]))

# Apply capping
cap_outliers(df, 'Total_Income')

plt.figure(figsize=(12,5))

# Boxplot after
plt.subplot(1,2,1)
sns.boxplot(x=df['Total_Income'])
plt.title('After Outlier Treatment - Boxplot')

# Histogram after
plt.subplot(1,2,2)
sns.histplot(df['Total_Income'], kde=True, bins=30)
plt.title('After Outlier Treatment - Distribution')

plt.show()

df.info()

df.to_csv("Cleaned_Loan_Bank_Data.csv", index=False)

df.head()

df = df.replace({'Y':1, 'N':0})

df.head()

df['Loan_to_Income_Ratio'] = np.where(df['Total_Income'] > 0, df['LoanAmount'] / df['Total_Income'], 0)

df.head()

# Calculate Total Applications (N)
total_applications = df.shape

# Calculate Overall Approval Rate (Mean of the binary column)
overall_approval_rate = df['Loan_Status'].mean()

# Calculate Average Financials
avg_loan_amount = df['LoanAmount'].mean()
avg_total_income = df['Total_Income'].mean()

# Print the results for the KPI cards
print("\n--- Executive KPI Results ---")
print(f"Total Applications (N): {total_applications}")
print(f"Overall Approval Rate: {overall_approval_rate:.2%}")
print(f"Average Loan Amount: ${avg_loan_amount:,.2f}K")
print(f"Average Total Income: ${avg_total_income:,.2f}")

df.head()

